stages:
  - build
docker-build:
  image: docker:19.03
  stage: build
  script:
    - export TAG_NAME=`git rev-parse HEAD`
    - export DOCKER_USER=$DOCKER_USER
    - export DOCKER_PASSWORD=$DOCKER_PASSWORD
    - ./build_script.sh
  only:
    - tags
