stages:
  - build
docker-build:
  image: docker:19.03
  stage: build
  script:
    - export GITLAB_USER=$GITLAB_USER
    - export GITLAB_PASSWORD=$GITLAB_PASSWORD
    - ./build_script.sh
  only:
    - tags
