version: '2'
services:
  backup:
    build: ./backup
    volumes:
      - ./data:/home/data
      - ~/.config/rclone:/root/.config/rclone
    environment:
      - REMOTE=scaleway
      - BUCKET=server-backups
      - DIRECTORY=test-101
      - NAME=backupdb
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=helloworld
      - CRON_SCHEDULE=0 23 * * *
      - START_NOW=yes
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=helloworld
      - MYSQL_DATABASE=test
